import Head from 'next/head'
import {
  AppstoreOutlined,
  ContainerOutlined,
  MenuFoldOutlined,
  PieChartOutlined,
  MenuUnfoldOutlined,
  DesktopOutlined,
  MailOutlined
} from '@ant-design/icons';
import { Button, Menu } from 'antd';
import { useEffect, useState } from 'react';
import { GetServerSideProps } from 'next'
import {useWindowWide} from "../src/js/utils/Util"
import { getAllCategory } from '@/js/apiService/ApiService'

function getItem(label, key, icon, children, type) {
  return {key,icon,children,label,type};
}

// const items = [getItem('Home', '1')];

export default function Home({listCategory}) {
  const [collapsed, setCollapsed] = useState(false);
  const toggleCollapsed = () => {
    setCollapsed(!collapsed);
  };
  const [items, setItems] = useState([getItem('Home', '0')]);
  useEffect(()=>{
    let list = [...items, listCategory.map(category =>{
      return getItem(category.name, category.id)
    })]
    setItems(list)
  }, [])
  const wide = useWindowWide(992)

  return (
    <>
      <Head>
        <title>Manga chy</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>
      <main >
        <div>
          {!collapsed ? <Menu
            mode={wide ? "horizontal": "vertical"}
            theme="light"
            items={items} 
          />: null}
          {!wide ? <Button
            type="primary"
            onClick={toggleCollapsed}
            style={{
              marginBottom: 16,
            }}
          >
            {collapsed ? <MenuUnfoldOutlined /> : <MenuFoldOutlined />}
          </Button>: null}
        </div>
      </main>
    </>
  )
}

export async function getServerSideProps() {
  let listCategory = await getAllCategory()
  
  return {
      props: {
          listCategory
      }
  }
}
